[sources.journald]
type = "journald"
current_boot_only = false

[transforms.filter_milvus_services]
type = "filter"
inputs = ["journald"]
condition = '''
exists(.SYSTEMD_UNIT) && (
  starts_with(string!(.SYSTEMD_UNIT), "milvus-") ||
  starts_with(string!(.SYSTEMD_UNIT), "nginx") ||
  starts_with(string!(.SYSTEMD_UNIT), "podman")
)
'''

[transforms.format_for_analytics]
type = "remap"
inputs = ["filter_milvus_services"]
source = '''
# Transform to match analytics-ops cf_logs format
.timestamp = format_timestamp!(.TIMESTAMP, format: "%+")
.app = "milvus"
.level = .PRIORITY
.message = del(.MESSAGE)
.service = del(.SYSTEMD_UNIT)
.host = del(._HOSTNAME)
.instance_id = .host
'''

[sinks.analytics_ops]
type = "http"
method = "post"
inputs = ["format_for_analytics"]
encoding.codec = "json"
uri = "https://vector-dev-yral.fly.dev"
healthcheck.enabled = true
request.timeout_secs = 60
batch.max_events = 1

[sinks.console]
type = "console"
inputs = ["format_for_analytics"]
encoding.codec = "json"
